name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  var1: value1
  vmImage: ubuntu-latest




jobs:
- job: Build
  steps:
  - script: echo First step!

- deployment: 'Deploy to Test'        # instead of job keyword, use deployment keyword
  pool:
    vmImage: '$(vmImage)'
  environment: test
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo Hi!
