name: $(appName)$(Date:yyyyMMdd)$(Rev:.r)

variables:
  appName: 'salesforce-monitoring'
  vmImage: 'ubuntu-latest'
  azureSubscription: 'visma-private-msdn'
  armStorage: 'corearmtemplates'
  resourceGroupName: $(Environment.Name)-$(appName)

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    pool:
      vmImage: '$(vmImage)'
    steps:

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/templates'
        artifactName: templates

- stage: 'Deployment'
  jobs:
  - deployment: 'Deploy_Test'
    pool:
      vmImage: '$(vmImage)'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadPipelineArtifact@2

          - task: AzureResourceGroupDeployment@2
            displayName: 'Provisioning infrastructure'
            inputs:
              azureSubscription: '$(azureSubscription)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: 'West Europe'
              csmFile: $(Pipeline.Workspace)/templates/azuredeploy.json
              csmParametersFile: $(Pipeline.Workspace)/templates/azuredeploy.parameters.json
              overrideParameters: -environment $(Environment.Name) -appName $(appName)
              deploymentMode: Incremental
