name: $(appName)$(Date:yyyyMMdd)$(Rev:.r)

variables:
  appName: 'salesforce-monitoring'
  vmImage: 'windows-latest'
  azureSubscription: 'visma-private-msdn'
  armStorage: 'corearmtemplates'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    pool:
      vmImage: '$(vmImage)'
    steps:
    - script: 'echo First step!'
    - task: AzureFileCopy@3
      inputs:
        sourcePath: 'templates'
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(armStorage)
        ContainerName: 'staging'
        outputStorageUri: 'artifactsLocation'
        outputStorageContainerSasToken: 'artifactsLocationSasToken'
        sasTokenTimeOutInMinutes: '240'

- stage: 'Deployment'
  jobs:
  - deployment: 'Deploy_Test'
    pool:
      vmImage: '$(vmImage)'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: 'echo Hi!'

          - task: AzureResourceGroupDeployment@2
            displayName: 'Provision Web App Dev'
            inputs:
              azureSubscription: '$(azureSubscription)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(Environment.Name)-$(appName)
              location: 'West Europe'
              csmFile: 'templates/azuredeploy.json'
              csmParametersFile: 'templates/azuredeploy.parameters.json'
              overrideParameters: -environment $(Release.EnvironmentName)
              deploymentMode: Incremental
