name: $(appName)$(Date:yyyyMMdd)$(Rev:.r)

variables:
  appName: 'salesforce-monitoring'
  vmImage: 'windows-latest'
  azureSubscription: 'visma-private-msdn'
  armStorage: 'corearmtemplates'
  resourceGroupName: $(Environment.Name)-$(appName)

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    pool:
      vmImage: '$(vmImage)'
    steps:

    - task: AzureFileCopy@3
      inputs:
        sourcePath: 'templates'
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(armStorage)
        ContainerName: 'staging'
        outputStorageUri: 'artifactsLocation'
        outputStorageContainerSasToken: 'artifactsLocationSasToken'
        sasTokenTimeOutInMinutes: '240'

- stage: 'Deployment'
  jobs:
  - deployment: 'Deploy_Test'
    pool:
      vmImage: '$(vmImage)'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureResourceGroupDeployment@2
            displayName: 'Provision Web App Dev'
            inputs:
              azureSubscription: '$(azureSubscription)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: 'West Europe'
              templateLocation: 'URL of the file'
              csmFileLink: $(artifactsLocation)staging/deployment.json$(artifactsLocationSasToken)
              csmParametersFileLink: $(artifactsLocation)staging/deployment.parameters.json$(artifactsLocationSasToken)
              overrideParameters: -environment $(Release.EnvironmentName)
              deploymentMode: Incremental
