name: $(appName)$(Date:yyyyMMdd)$(Rev:.r)

variables:
  appName: 'salesforce-monitoring'
  vmImage: 'ubuntu-latest'
  azureSubscription: 'visma-private-msdn'
  armStorage: 'corearmtemplates'


jobs:
- job: 'Build'
  steps:
  - script: 'echo First step!'
  - task: AzureFileCopy@4
    inputs:
      sourcePath: 'templates'
      azureSubscription: $(azureSubscription)
      destination: azureBlob
      sotorage: $(armStorage)
      containerName: $(Build.BuildNumber)



- deployment: 'Deploy to Test'        # instead of job keyword, use deployment keyword
  pool:
    vmImage: '$(vmImage)'
  environment: 'test'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: 'echo Hi!'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Provision Web App Dev'
          inputs:
            azureSubscription: '$(azureSubscription)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: $(Release.EnvironmentName)-$(appName)
            location: 'UK West'
            csmFile: 'templates/azuredeploy.json'
            csmParametersFile: 'templates/azuredeploy.parameters.json'
            overrideParameters: -environment $(Release.EnvironmentName)
            deploymentMode: Incremental
