name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  var1: value1




jobs:
- job: Build
  steps:
  - script: echo First step!

- deployment: Test        # instead of job keyword, use deployment keyword
  pool:
    name: string
    demands: string | [ string ]
  environment: test
  strategy:
    runOnce:
      deploy:
        steps:
          
        - script: echo Hi!
